apiVersion: v1
kind: Service
metadata:
  name: gitlab-nodeport
  namespace: gitlab
  labels:
    name: gitlab
  annotations:
    metallb.universe.tf/address-pool: production
spec:
  type: LoadBalancer  # Change to LoadBalancer to work with MetalLB
  selector:
    name: gitlab
  ports:
    - name: ssh
      port: 22
      targetPort: ssh
    - name: http
      port: 80
      targetPort: http
  loadBalancerIP: 172.16.1.236  # Assigning the static IP
